name: Deploy Pages

on:
  push:
    branches: ["main"]
    workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cargo install mdbook
      - run: mdbook build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'book/'
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v5
